jsjdfalpkfdsajassdlkfoajfdsaplasfdjalkpasfdjaalfsdpkajfdesaldipjfdsadlpsfdajlpfsda
Run west build -s zmk/app -d "/tmp/tmp.XugbD09fTo" -b "nice_nano"  -- -DZMK_CONFIG=/tmp/zmk-config/config -DSHIELD="corne_left nice_view" -DZMK_EXTRA_MODULES='/__w/zmk-config/zmk-config'
+ west build -s zmk/app -d /tmp/tmp.XugbD09fTo -b nice_nano -- -DZMK_CONFIG=/tmp/zmk-config/config -DSHIELD=corne_left nice_view -DZMK_EXTRA_MODULES=/__w/zmk-config/zmk-config
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /tmp/zmk-config/zmk/app
-- CMake version: 3.31.6
-- Found Python3: /usr/bin/python3 (found suitable version "3.12.3", minimum required is "3.10") found components: Interpreter
-- Cache files will be written to: /tmp/zmk-config/zephyr/.cache
-- Zephyr version: 4.1.0 (/tmp/zmk-config/zephyr)
-- Found west (found suitable version "1.5.0", minimum required is "0.14.0")
-- Board: nice_nano, Revision: 2.0.0, qualifiers: nrf52840
-- Shield(s): corne_left nice_view
Checking /tmp/zmk-config/zmk-nice-oled
Checking /__w/zmk-config/zmk-config
Checking /tmp/zmk-config/zmk/app
found /tmp/zmk-config/zmk/app
-- ZMK Config directory: /tmp/zmk-config/config
-- ZMK Config Kconfig: /tmp/zmk-config/config/corne.conf
nice_nano_nrf52840 for _nrf52840 for nice_nano with version 2.0.0
-- Using keymap file: /tmp/zmk-config/config/corne.keymap
-- Using keymap file: /tmp/zmk-config/config/corne.keymap
Checking /tmp/zmk-config/zephyr
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.9 (/opt/zephyr-sdk-0.16.9)
-- Found toolchain: zephyr 0.16.9 (/opt/zephyr-sdk-0.16.9)
-- Found Dtc: /opt/zephyr-sdk-0.16.9/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
-- Found BOARD.dts: /tmp/zmk-config/zmk/app/boards/nicekeyboards/nice_nano/nice_nano.dts
-- Found devicetree overlay: /tmp/zmk-config/zmk/app/boards/nicekeyboards/nice_nano/nice_nano_2_0_0.overlay
-- Found devicetree overlay: /tmp/zmk-config/zmk/app/boards/shields/corne/corne_left.overlay
-- Found devicetree overlay: /tmp/zmk-config/zmk/app/boards/shields/corne/boards/nice_nano.overlay
-- Found devicetree overlay: /tmp/zmk-config/zmk/app/boards/shields/nice_view/nice_view.overlay
-- Found devicetree overlay: /tmp/zmk-config/config/corne.keymap
devicetree error: /tmp/zmk-config/zmk/app/boards/shields/nice_view/nice_view.overlay:7 (column 1): parse error: undefined node label 'nice_view_spi'
CMake Error at /tmp/zmk-config/zephyr/cmake/modules/dts.cmake:303 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"

Call Stack (most recent call first):
  /tmp/zmk-config/zephyr/cmake/modules/zephyr_default.cmake:134 (include)
  /tmp/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /tmp/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/tmp/tmp.XugbD09fTo -GNinja -DBOARD=nice_nano -DZMK_CONFIG=/tmp/zmk-config/config '-DSHIELD=corne_left nice_view' -DZMK_EXTRA_MODULES=/__w/zmk-config/zmk-config -S/tmp/zmk-config/zmk/app